<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { gsap } from 'gsap'
import {
  LayoutDashboard, GraduationCap, CalendarCheck, WalletCards, ChartNoAxesCombined,
  Search, Bell, ChevronDown, ArrowUpRight, Users, UserRoundCheck, BookOpenCheck,
  CircleDollarSign, MoreHorizontal, Plus, SlidersHorizontal, Download, Check,
  Clock3, X, Menu, Sparkles, TrendingUp, CircleHelp
} from 'lucide-vue-next'

type Section = 'Dashboard' | 'Grades' | 'Attendance' | 'Tuition' | 'Statistics'
const active = ref<Section>('Dashboard')
const mobileOpen = ref(false)
const search = ref('')
const attendance = ref<Record<string, string>>({ Ava: 'Present', Noah: 'Late', Mia: 'Present', Liam: 'Absent', Zoe: 'Present' })
const sections: { name: Section; icon: any }[] = [
  { name: 'Dashboard', icon: LayoutDashboard }, { name: 'Grades', icon: GraduationCap },
  { name: 'Attendance', icon: CalendarCheck }, { name: 'Tuition', icon: WalletCards },
  { name: 'Statistics', icon: ChartNoAxesCombined },
]
const students = [
  { name: 'Ava Thompson', initials: 'AT', class: 'Grade 8 · A', assignment: 'Mathematics', score: 92, trend: '+4.2%', color: 'coral' },
  { name: 'Noah Williams', initials: 'NW', class: 'Grade 7 · B', assignment: 'Science', score: 87, trend: '+2.8%', color: 'blue' },
  { name: 'Mia Anderson', initials: 'MA', class: 'Grade 9 · A', assignment: 'English Literature', score: 78, trend: '-1.4%', color: 'gold' },
  { name: 'Liam Martinez', initials: 'LM', class: 'Grade 8 · C', assignment: 'History', score: 96, trend: '+6.1%', color: 'green' },
]
const attendanceRows = computed(() => students.map((s) => ({ ...s, status: attendance.value[s.name.split(' ')[0]] || 'Present' })))
const filteredStudents = computed(() => students.filter(s => `${s.name} ${s.assignment}`.toLowerCase().includes(search.value.toLowerCase())))
const setStatus = (first: string, status: string) => { attendance.value = { ...attendance.value, [first]: status } }
const nav = (name: Section) => { active.value = name; mobileOpen.value = false }
onMounted(() => { gsap.from('.app-shell', { opacity: 0, y: 12, duration: .55, ease: 'power2.out' }) })
</script>

<template>
  <div class="app-shell min-h-screen bg-[#f5f7fb] text-[#17213b]">
    <aside :class="['sidebar', { 'sidebar-open': mobileOpen }]">
      <div class="brand"><div class="brand-mark"><span></span><span></span><span></span></div><span>Edu<span>SaaS</span></span></div>
      <div class="school-switch"><div class="school-logo">W</div><div><strong>Westfield Academy</strong><small>Admin workspace</small></div><ChevronDown :size="15" /></div>
      <nav class="nav-list" aria-label="Main navigation"><p class="nav-label">Workspace</p><button v-for="item in sections" :key="item.name" :class="['nav-item', { active: active === item.name }]" @click="nav(item.name)"><component :is="item.icon" :size="19" /><span>{{ item.name }}</span><span v-if="item.name === 'Attendance'" class="nav-dot"></span></button></nav>
      <div class="sidebar-bottom"><div class="upgrade"><Sparkles :size="18" /><strong>Unlock more</strong><p>Get deeper insights with Pro.</p><button>Explore plans <ArrowUpRight :size="14" /></button></div><button class="help"><CircleHelp :size="18" /> Help center</button><div class="user-mini"><div class="avatar purple">JD</div><div><strong>Jordan Davis</strong><small>School admin</small></div><MoreHorizontal :size="18" /></div></div>
    </aside>
    <div v-if="mobileOpen" class="scrim" @click="mobileOpen=false"></div>
    <main class="main-content">
      <header class="topbar"><button class="mobile-menu" @click="mobileOpen=true"><Menu :size="21" /></button><div class="crumb"><span>Workspace</span><span>/</span><strong>{{ active }}</strong></div><div class="top-actions"><div class="search-box"><Search :size="17" /><input v-model="search" placeholder="Search anything..." aria-label="Search" /><kbd>⌘ K</kbd></div><button class="icon-button notification"><Bell :size="19" /><i></i></button><div class="top-avatar">JD</div></div></header>
      <Transition name="fade" mode="out-in"><div :key="active" class="page-wrap">
        <section class="page-heading"><div><p class="eyebrow">{{ active === 'Dashboard' ? 'Tuesday, October 24, 2024' : 'Workspace overview' }}</p><h1>{{ active === 'Dashboard' ? 'Good morning, Jordan' : active }}</h1><p class="subheading">{{ active === 'Dashboard' ? 'Here’s what’s happening across your school today.' : `Monitor and manage your school’s ${active.toLowerCase()} in one place.` }}</p></div><div class="heading-actions"><button class="button ghost"><Download :size="16" /> Export</button><button class="button primary"><Plus :size="17" /> {{ active === 'Attendance' ? 'Take attendance' : 'Add new' }}</button></div></section>
        <div v-if="active === 'Dashboard'" class="dashboard-view">
          <section class="kpi-grid"><article class="kpi-card"><div class="kpi-icon indigo"><Users :size="19" /></div><div class="kpi-title">Total students <ArrowUpRight :size="15" /></div><strong>1,248</strong><p><b class="up">+8.2%</b> <span>vs last month</span></p><div class="sparkline indigo-line"><span v-for="h in [20,27,22,34,28,42,37,51,44,61,56,75]" :key="h" :style="{height: h+'%'}"></span></div></article><article class="kpi-card"><div class="kpi-icon emerald"><UserRoundCheck :size="19" /></div><div class="kpi-title">Attendance rate <ArrowUpRight :size="15" /></div><strong>94.8%</strong><p><b class="up">+1.6%</b> <span>vs last month</span></p><div class="sparkline green-line"><span v-for="h in [34,45,38,49,42,57,48,63,57,69,64,78]" :key="h" :style="{height: h+'%'}"></span></div></article><article class="kpi-card tuition-kpi"><div class="kpi-icon amber"><CircleDollarSign :size="19" /></div><div class="kpi-title">Tuition collected <ArrowUpRight :size="15" /></div><strong>$428,650</strong><p><b class="up">+12.4%</b> <span>vs last month</span></p><div class="ring-wrap"><svg viewBox="0 0 42 42"><circle class="ring-bg" cx="21" cy="21" r="15.5" /><circle class="ring-fill" cx="21" cy="21" r="15.5" /></svg><b>78%</b></div></article><article class="kpi-card"><div class="kpi-icon coral"><BookOpenCheck :size="19" /></div><div class="kpi-title">Active classes <ArrowUpRight :size="15" /></div><strong>48</strong><p><b class="neutral">+2</b> <span>new this term</span></p><div class="mini-bars"><i v-for="h in [38,52,43,68,57,83,70,92]" :key="h" :style="{height:h+'%'}"></i></div></article></section>
          <section class="content-grid"><article class="panel grades-panel"><div class="panel-head"><div><h2>Student grades</h2><p>Latest academic performance across classes</p></div><button class="text-button" @click="active='Grades'">View all <ArrowUpRight :size="15" /></button></div><div class="table-wrap"><table><thead><tr><th>Student</th><th>Subject</th><th>Score</th><th>Trend</th></tr></thead><tbody><tr v-for="s in students.slice(0,3)" :key="s.name"><td><div class="person"><div :class="['avatar', s.color]">{{ s.initials }}</div><div><strong>{{ s.name }}</strong><small>{{ s.class }}</small></div></div></td><td>{{ s.assignment }}</td><td><div class="score"><b>{{ s.score }}%</b><div class="progress"><i :style="{width:s.score+'%'}"></i></div></div></td><td><span :class="s.trend.startsWith('+') ? 'up' : 'down'">{{ s.trend }}</span></td></tr></tbody></table></div></article><article class="panel attendance-panel"><div class="panel-head"><div><h2>Today’s attendance</h2><p>Monday, October 24</p></div><button class="round-button"><MoreHorizontal :size="18" /></button></div><div class="attendance-overview"><div class="attendance-circle"><svg viewBox="0 0 100 100"><circle cx="50" cy="50" r="41" /><circle class="att-fill" cx="50" cy="50" r="41" /></svg><strong>94.8<small>%</small></strong><span>Present today</span></div><div class="legend"><div><i class="dot green-dot"></i><span>Present</span><b>1,184</b></div><div><i class="dot amber-dot"></i><span>Late</span><b>38</b></div><div><i class="dot red-dot"></i><span>Absent</span><b>26</b></div></div></div><button class="full-button" @click="active='Attendance'">Manage attendance <ArrowUpRight :size="15" /></button></article></section>
          <section class="bottom-grid"><article class="panel chart-panel"><div class="panel-head"><div><h2>Attendance overview</h2><p>Daily attendance rate over the last 7 days</p></div><button class="select-button">This week <ChevronDown :size="15" /></button></div><div class="chart"><div class="y-labels"><span>100%</span><span>95%</span><span>90%</span><span>85%</span></div><svg viewBox="0 0 700 220" preserveAspectRatio="none"><defs><linearGradient id="chartFill" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stop-color="#5664e8" stop-opacity=".2"/><stop offset="1" stop-color="#5664e8" stop-opacity="0"/></linearGradient></defs><path class="area" d="M0,104 C45,110 58,77 105,87 S155,125 210,99 S260,76 315,89 S365,54 420,74 S475,102 525,69 S580,35 630,58 S675,42 700,31 L700,220 L0,220 Z"/><path class="line" d="M0,104 C45,110 58,77 105,87 S155,125 210,99 S260,76 315,89 S365,54 420,74 S475,102 525,69 S580,35 630,58 S675,42 700,31"/><circle cx="630" cy="58" r="5" /></svg><div class="x-labels"><span>Mon</span><span>Tue</span><span>Wed</span><span>Thu</span><span>Fri</span><span>Sat</span><span>Sun</span></div></div></article><article class="panel events-panel"><div class="panel-head"><div><h2>Upcoming events</h2><p>Keep an eye on what’s next</p></div><button class="round-button"><MoreHorizontal :size="18" /></button></div><div class="event"><div class="date-block"><b>26</b><span>OCT</span></div><div><strong>Parent–Teacher Conference</strong><small>Thursday · 9:00 AM – 4:00 PM</small></div><ArrowUpRight :size="15" /></div><div class="event"><div class="date-block blue-date"><b>30</b><span>OCT</span></div><div><strong>Midterm examinations begin</strong><small>Monday · All day</small></div><ArrowUpRight :size="15" /></div><button class="full-button secondary-button">View calendar <ArrowUpRight :size="15" /></button></article></section>
        </div>
        <section v-else-if="active === 'Grades'" class="panel page-panel"><div class="panel-head"><div><h2>Academic performance</h2><p>Track scores and progress by student</p></div><button class="select-button"><SlidersHorizontal :size="15" /> Filter</button></div><div class="table-wrap large-table"><table><thead><tr><th>Student</th><th>Subject</th><th>Score</th><th>Progress</th><th>Status</th></tr></thead><tbody><tr v-for="s in filteredStudents" :key="s.name"><td><div class="person"><div :class="['avatar', s.color]">{{ s.initials }}</div><div><strong>{{ s.name }}</strong><small>{{ s.class }}</small></div></div></td><td>{{ s.assignment }}</td><td><b>{{ s.score }}%</b></td><td><div class="score"><div class="progress wide"><i :style="{width:s.score+'%'}"></i></div></div></td><td><span :class="['status-badge', s.score > 90 ? 'success' : s.score > 80 ? 'info' : 'warning']">{{ s.score > 90 ? 'Excellent' : s.score > 80 ? 'On track' : 'Needs focus' }}</span></td></tr></tbody></table></div></section>
        <section v-else-if="active === 'Attendance'" class="panel page-panel"><div class="panel-head"><div><h2>Daily attendance</h2><p>Grade 8 · Section A · Monday, October 24</p></div><button class="select-button">Today <ChevronDown :size="15" /></button></div><div class="attendance-summary"><div><span class="dot green-dot"></span><b>Present</b><strong>24</strong></div><div><span class="dot amber-dot"></span><b>Late</b><strong>2</strong></div><div><span class="dot red-dot"></span><b>Absent</b><strong>1</strong></div></div><div class="attendance-list"><div v-for="row in attendanceRows" :key="row.name" class="attendance-row"><div class="person"><div :class="['avatar', row.color]">{{ row.initials }}</div><div><strong>{{ row.name }}</strong><small>{{ row.class }}</small></div></div><div class="toggle-set"><button v-for="status in ['Present','Late','Absent']" :key="status" :class="[{ selected: row.status === status }, status.toLowerCase()]" @click="setStatus(row.name.split(' ')[0], status)">{{ status === 'Present' ? 'P' : status === 'Late' ? 'L' : 'A' }} <span>{{ status }}</span></button></div></div></div></section>
        <section v-else-if="active === 'Tuition'" class="tuition-view"><div class="kpi-grid tuition-grid"><article class="kpi-card"><div class="kpi-icon indigo"><CircleDollarSign :size="19" /></div><div class="kpi-title">Total billed</div><strong>$548,000</strong><p><span>Fall 2024 term</span></p></article><article class="kpi-card"><div class="kpi-icon emerald"><Check :size="19" /></div><div class="kpi-title">Collected</div><strong>$428,650</strong><p><b class="up">78.2%</b> <span>of total billed</span></p></article><article class="kpi-card"><div class="kpi-icon amber"><Clock3 :size="19" /></div><div class="kpi-title">Outstanding</div><strong>$119,350</strong><p><b class="warning-text">142 families</b> <span>with balance</span></p></article></div><article class="panel chart-panel"><div class="panel-head"><div><h2>Collection performance</h2><p>Monthly tuition collected vs outstanding</p></div><button class="select-button">This year <ChevronDown :size="15" /></button></div><div class="finance-chart"><div v-for="(month, i) in ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct']" :key="month" class="finance-col"><div class="bars"><i :style="{height: [45,58,51,68,62,74,80,67,88,94][i]+'%'}"></i><i :style="{height: [22,18,29,20,27,16,12,19,10,8][i]+'%'}"></i></div><span>{{ month }}</span></div></div><div class="chart-key"><span><i class="key-indigo"></i>Collected</span><span><i class="key-amber"></i>Outstanding</span></div></article></section>
        <section v-else class="stats-view"><div class="stats-cards"><article class="stat-highlight"><div><span>Academic growth index</span><strong>+18.6%</strong><p><TrendingUp :size="15" /> Stronger than last term</p></div><div class="predictive-line"><svg viewBox="0 0 260 90" preserveAspectRatio="none"><path d="M0 76 C25 70, 35 57, 58 63 S90 55, 110 58 S130 39, 154 45 S178 38, 192 41 S220 18, 260 8"/></svg></div></article><article class="stat-highlight teal"><div><span>Student engagement</span><strong>86.4%</strong><p><TrendingUp :size="15" /> +5.2% from September</p></div><div class="predictive-line"><svg viewBox="0 0 260 90" preserveAspectRatio="none"><path d="M0 65 C30 74, 40 43, 66 53 S98 28, 120 42 S153 28, 178 34 S214 15, 260 20"/></svg></div></article></div><div class="stats-grid"><article class="panel stat-panel"><div class="panel-head"><div><h2>Performance by subject</h2><p>Average class score distribution</p></div></div><div class="horizontal-bars"><div v-for="item in [['Mathematics',86,'#5967e9'],['Science',82,'#3fb88d'],['English',78,'#eead54'],['History',74,'#f07868'],['Arts',91,'#9c7eea']]" :key="item[0]"><span>{{ item[0] }}</span><div><i :style="{width:item[1]+'%',background:item[2]}"></i></div><b>{{ item[1] }}%</b></div></div></article><article class="panel stat-panel donut-panel"><div class="panel-head"><div><h2>Enrollment mix</h2><p>Students by grade level</p></div></div><div class="donut-chart"><svg viewBox="0 0 100 100"><circle cx="50" cy="50" r="34"/><circle class="d1" cx="50" cy="50" r="34"/><circle class="d2" cx="50" cy="50" r="34"/><circle class="d3" cx="50" cy="50" r="34"/></svg><strong>1,248<small>students</small></strong></div><div class="donut-legend"><span><i class="dot dot-indigo"></i>Grade 6–7 <b>32%</b></span><span><i class="dot green-dot"></i>Grade 8–9 <b>41%</b></span><span><i class="dot amber-dot"></i>Grade 10–12 <b>27%</b></span></div></article></div></section>
      </div></Transition>
    </main>
  </div>
</template>
